
services:
  python-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    image: registry.lemontree.local/python-dev:latest
    container_name: python-dev
    volumes:
      - ../:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "python /workspace/app/app.py && tail -f /dev/null"
