
services:
  # python-dev:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: registry.lemontree.local/python-dev:latest
  #   container_name: python-dev
  #   volumes:
  #     - ../:/workspace
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   command: sh -c "python /workspace/app/app.py && tail -f /dev/null"

  netbox:
    build: 
      context: .
      dockerfile: Dockerfile
      image: registry.lemontree.local/python-dev:latest
    container_name: netbox
    ports:
      - "8000:8080"
    env_file: ./netbox.env
    volumes:
      - netbox-media:/opt/netbox/netbox/media
      # - ../plugins:/opt/netbox/netbox/plugins
      - ../:/workspace
    depends_on:
      - postgres
      - redis
    entrypoint: []                # Clear any upstream entrypoint
    command:                      # This is passed as "$@" to dev-entrypoint.sh
      - /opt/netbox/venv/bin/python3
      - /opt/netbox/netbox/manage.py
      - runserver
      - 0.0.0.0:8080

  postgres:
    image: postgres:17.5-alpine
    container_name: netbox-postgres
    env_file: ./netbox.env
    volumes:
      - netbox_db_data:/var/lib/postgresql/data
    
  redis:
    image: redis:8.0.3-alpine
    container_name: netbox-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: ./netbox.env
    volumes:
      - netbox_redis_data:/data

volumes:
  netbox-media:
    name: netbox_media
  netbox_db_data:
    name: netbox_db_data
  netbox_redis_data:
    name: netbox_redis_data