
services:
  postgres:
    image: postgres:alpine
    container_name: netbox-postgres
    env_file: 
      - netbox.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: netbox-redis
    env_file: 
      - netbox.env
    command: redis-server --save 60 1 --loglevel warning

  netbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: netbox-dev:slim
    container_name: netbox
    env_file: 
      - netbox.env
    depends_on:
      - postgres
      - redis
    volumes:
      - netbox_media:/opt/netbox/netbox/media
      - netbox_static:/opt/netbox/netbox/static
      - ../plugins:/opt/netbox/netbox/plugins:cached
    ports:
      - "8000:8000"
      - "5678:5678"

volumes:
  postgres_data:
  netbox_media:
  netbox_static:
